Flo evaluation
floschne/NLP_ProjectLSIRES pull request #14
Opened 2018-01-24 19:25 UTC by floschne

2018-01-25 18:41 UTC, pikant approved these changes

2018-01-25 18:43 UTC, julianbetz requested changes
Minor changes necessary

2018-01-25 18:43 UTC, julianbetz commented on dev/core/src/main/java/data/input/PopularWikiArticlesReader.java
> +    private IWikiArticleLoader IWikiArticleLoader;
Attribute renamed to an uppercase name. This may result in wrong interpretations of the variable IWikiArticle in the remaining code.

2018-01-25 18:43 UTC, julianbetz commented on dev/core/src/main/java/eval/LanguageDetectionEvaluationPipeline.java
> +        System.out.println("Use DummyLanguageDetector (0, 1)?");
Underspecified: What does DummyLanguageDetector do? What is the alternative?
A user might be confused by this prompt.

2018-01-28 16:27 UTC, floschne commented on dev/core/src/main/java/data/input/PopularWikiArticlesReader.java
> +    private IWikiArticleLoader IWikiArticleLoader;
done

2018-01-28 16:27 UTC, floschne commented on dev/core/src/main/java/eval/LanguageDetectionEvaluationPipeline.java
> +        System.out.println("Use DummyLanguageDetector (0, 1)?");
done

2018-01-29 09:08 UTC, pikant approved these changes

2018-01-29 09:18 UTC, merged